### ISSUE TITLE
MCQs on Keywords and Identifiers

### ISSUE THREAD

**Issue by gunjanbangde** [Python-by-codemistic/8-weeks-of-python#2]
**1. Which of the following is not valid variable name in Python?**
A. 11var
B. var_name
C. _var
D. (var)

**2. How many keywords are there in python 3.7?**
A. 32
B. 35
C. 31
D. 33

**3. What is the maximum length of an identifier in python?**
A. 128
B. 31
C. 64
D. None of the above

**4. Which one of the following will give an error in python?**
A. x=’Hello’
B. true=0
C. Var1=”@gmail”
D. None of the above

**5. Which of the following statment is False?**
A. Variable names can be arbitrarily long.
B. They can contain both letters and numbers.
C. Variable name can begin with number.
D. Variable name can begin with underscore.

**Comment by gantavyamalviya** [comment]
### Comment your Answers in this format :

**Name:-** 
**Branch and Year:-**
**College:-**

Answers:- 
> 

1. 
2.
3.
4.
5.

**Comment by AyanKhan2077** [comment]
Name:- Mohd Ayan Khan
Branch and Year:- CSE -2 year
College:-LNCT
Answers:-
1.A
2.B
3.D
4.D
5.C

**Comment by Jaiswal14** [comment]
Name : Mohit Kumar Jaiswal
Branch and year : CSE / 3rd
College : LNCTE
Answers :
1. A
2. B
3. D
4. D
5. C

**Comment by sakshi-jain24** [comment]
Name:- Sakshi Jain 
Branch and Year:- CSE-3 year
College:- Samrat ashoka technological institute VIDISHA 
Answers:-
1.A
2. B
3.D
4.D
5.C

**Comment by drashijain09** [comment]
Name:- Drashi Jain
Branch & year :- CSE & 3rd year
College :- LNCTE, Bhopal
Answers:-
1.A
2. B
3. D
4. D
5. C

**Comment by Sahil729** [comment]
1-A
2-B
3-D
4-D
5-C

**Comment by anant1815** [comment]
Name:-Anant Priyadarshi
Branch and Year:- CSE  2nd yr (3rd sem)
College:-LNCTS
Answers:-
1.A
2.B
3.D
4.D
5.C

**Comment by Divyanshupatil** [comment]
Name-divyanshu Patil
Branch and year - EC and 2nd
College - LNCT Bhopal 
1.A
2.B
3.D
4.D
5.C

**Comment by sheetalparmar99** [comment]
Name : Sheetal Parmar 
Branch and Year : ECE 4th Year (7th Sem)
College : LNCTE
1.A
2.D
3.D
4.B
5.C

**Comment by AnuragKumar5** [comment]
Name:- Anurag Kumar
Branch and Year:- CSE , 2nd year
College:- LNCT

Answers:-

1. A
2. B
3. D
4. D
5. C

**Comment by MuskanAthghara** [comment]
Name- Muskan Athghara
Branch and year- CSE ,2nd year
College-LNCTS
Answers- 
1. A
2. B
3. D
4. D
5. C

**Comment by AyushPurwar525** [comment]
Name:- Ayush Purwar
Branch and Year:- ECE, 2nd year
College:- LNCT Bhopal
Answers:-
1. A
2. D
3. D
4. D
5. C

**Comment by THESHIVAMM** [comment]
Name : Shivansh Mishra
Branch & Year : IT / 3rd yr
College : LNCT BHOPAL

1. A and D
2. D
3. D
4. D
5. C

**Comment by manu-2611** [comment]
Name:- Madhup Shrivastava 
Branch & year :- CSE & 2rd year
College :- LNCTS, Bhopal
Answers:-
1.A
2. B
3. D
4. D
5. C

**Comment by sheetalparmar99** [comment]
1. Which of the following symbol are used for comment in python ?
A. #
B. " " "
C. A and B 
D. None of the above.
2. Most of the programming languages like C, C++, and Java use braces { } to define a block of code. Python, however, uses ________.
A. Indentation
B.Semi-Colon
C.Parentheses
D.None of the above
3. Which of the following will give error?
A. a=b=c=1
B. a,b,c=1
C. a,b,c=1, "Hello", 1.5
D. None of the above
4. Which one of the following is correct way of declaring and initialising a variable, x with value 5?
A. int x
 x=5
B. int x=5
C. x=5
D.declare x=5
5.A string is immutable in Python?
Every time when we modify the string, Python Always create a new String and assign a new string to that variable.
A. True.
B. False

**Comment by vanshika30** [comment]
Name:- Vanshika Kriplani
Branch and Year:- EC 2nd year
College:- LNCT

Answers:-
1. A
2. B
3. D
4. D
5. C

**Comment by satya-266** [comment]
NAME-Satya Priya
BRANCH & YEAR-MCA 2nd yr
COLLEGE-LNCT
1.A
2.B
3.D
4.D
5.C
